language: node_js
branches:
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '7.5'
before_script:
  - npm prune && npm cache clean
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
